### ISSUE TITLE
Closing events doesn't fire

### ISSUE THREAD

**Issue by drugoi** [wheely/ember-dialog#92] opened 2017-03-01 15:29 UTC
Hi,

I'm trying to use ember-dialog in my project, but when dialog is appearing at screen I can't close it (using OK button or X icon or clicking outside dialog).
In Event Listeners tab there is no click event on OK button
<img width="160" alt="screen shot 2017-03-01 at 9 24 22 pm" src="https://cloud.githubusercontent.com/assets/1858708/23466602/ccd8e9f0-fec5-11e6-8d61-fde4f2fb28e9.png">

Environment data:
```
Ember             : 2.11.2
jQuery            : 3.1.1
Ember Dialog      : 3.0.0-rc.8
```

It's depends on Ember version or this is a bug somewhere in plugin?

**Comment by ajile** [comment] 2017-03-01 16:01
Hi, thank you for your notice.

It seems like a bug. The `ember-dialog` works well with Ember v2.11.0, but it wasn't tested with Ember v2.11.2. In near future (next week) I will try to figure out why it's happening.

The dialog that appears is a simple Ember.Component (see [presenter](https://github.com/wheely/ember-dialog/blob/master/addon/components/presenter.js)) augmented by special mixin ([context](https://github.com/wheely/ember-dialog/blob/master/addon/mixins/context.js)) that added special actions to it. The actions are available in dialog's layout and template. If you want figure out why it's not working your own, you may start debugging there.

**Comment by ajile** [comment] 2017-03-06 12:43
I've tested the `ember-dialog` with the latest stable ember version (2.11.2) - it's working well. The buttons closes a window as expected. The clicking outside a dialog does not (as expected too).

@drugoi, could you reproduce a problem on https://ember-twiddle.com/?

**Comment by ajile** [comment] 2017-05-04 16:01
I'm closing the issue, because it could not be reproduced.

**Closed by ajile** 2017-05-04 16:01 UTC
